Repository layer5io/meshery-smp-action, pull requests merged in 2021-12, with the labels that each got.

#28 Ensure that Istio application endpoint is reachable from Meshery
  .github/workflows/scripts/istio_deploy.sh
Labels: area/devops

#30 update performance profile name and test name in scheduled benchmarks
  .github/workflows/scheduled-benchmarks.yml
  mesheryctl.sh
Labels: area/ci, pr/do-not-merge

#31 change script to check perf test config file
  mesheryctl.sh
Labels: area/ci

#32 Update profile name and fix port-forwarding
  .github/workflows/scheduled-benchmarks.yml
  .github/workflows/scripts/linkerd_deploy.sh
  .github/workflows/scripts/osm_deploy.sh
Labels: area/ci
